server:
  port: 8089
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    allow-session-override: true
    request-context-attribute: request
    template-loader-path: classpath:/templates
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/opinion_report?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    tomcat:
      max-active: 20
      max-wait: 60000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      host: localhost
      database: opinion_report_m
      port: 27017
      repositories:
        type: auto
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 0ms

