server:
  port: 8090
spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order:
    view-names:
    servlet:
      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/opinion_report?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    tomcat:
      max-active: 20
      max-wait: 60000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      host: localhost
      database: opinion_report_m
      port: 27017
      repositories:
        type: auto
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 0ms

